#!/bin/bash
job=$1

export ORIGIN_PYTHONPATH=$PYTHONPATH

#############
# BENCHMARK #
#############

# Make folder for models generated by the benchmark version of RMG-Py/RMG-database:
export benchmark_tests=$DATA_DIR/tests/benchmark/$benchmark_tag
mkdir -p $benchmark_tests/thermo_val_jobs/$job

cp $BASE_DIR/examples/thermo_val/$job/dataset.txt $benchmark_tests/thermo_val_jobs/$job/dataset.txt

echo "Benchmark Version of RMG: "$RMG_BENCHMARK
echo "Running thermo validation on benchmark version..."

source activate ${benchmark_env}
export PYTHONPATH=$RMG_BENCHMARK:$ORIGIN_PYTHONPATH

python $BASE_DIR/thermo_val/evaluate.py -d $benchmark_tests/thermo_val_jobs/$job/dataset.txt -pb $RMGPY_BENCHMARK_BRANCH -dbb $RMGDB_BENCHMARK_BRANCH -psha ${benchmark_py_sha} -dbsha ${benchmark_db_sha}

source deactivate
export PYTHONPATH=$ORIGIN_PYTHONPATH

###########
# TESTING #
###########

# Make folder for models generated by the test version of RMG-Py and RMG-database:
export testing_tests=$DATA_DIR/tests/testing/$testing_tag
mkdir -p $testing_tests/thermo_val_jobs/$job

cp $BASE_DIR/examples/thermo_val/$job/dataset.txt $testing_tests/thermo_val_jobs/$job/dataset.txt

echo "Testing Version of RMG: "$RMG_TESTING
echo "Running thermo validation on testing version..."

source activate ${testing_env}
export PYTHONPATH=$RMG_TESTING:$ORIGIN_PYTHONPATH 

python $BASE_DIR/thermo_val/evaluate.py -d $testing_tests/thermo_val_jobs/$job/dataset.txt -pb $RMGPY_TESTING_BRANCH -dbb $RMGDB_TESTING_BRANCH -psha ${testing_py_sha} -dbsha ${testing_db_sha}

source deactivate
export PYTHONPATH=$ORIGIN_PYTHONPATH
