#!/bin/bash

set -e
if [ -z ${RMG+x} ]; then 
	echo "RMG variable is unset. Exiting..."
	exit 0
fi

export ORIGIN_PYTHONPATH=$PYTHONPATH
echo "Running $1 example"

###########
#BENCHMARK#
###########
# make folder for models generated by the benchmark version of RMG-Py/RMG-database:
mkdir -p testing/benchmark/$1
rm -rf testing/benchmark/$1/*
cp examples/rmg/$1/input.py testing/benchmark/$1/input.py
source activate benchmark
echo "benchmark version of RMG: "$RMG_BENCHMARK

PYTHONPATH=$RMG_BENCHMARK:$ORIGIN_PYTHONPATH 

# use the rmgrc file to point to the location of the desired RMG-database:
rmgrc="database.directory : "$benchmark/RMG-database/input/
rm -rf $HOME/.rmg
mkdir -p $HOME/.rmg
echo $rmgrc >> $HOME/.rmg/rmgrc

python $RMG_BENCHMARK/rmg.py testing/benchmark/$1/input.py > /dev/null
source deactivate
PYTHONPATH=$ORIGIN_PYTHONPATH

#########
#TESTING#
#########
# make folder for models generated by the test version of RMG-Py and RMG-database:
mkdir -p testing/testmodel/$1
rm -rf testing/testmodel/$1/*
cp examples/rmg/$1/input.py testing/testmodel/$1/input.py
source activate testing
echo "test version of RMG: "$RMG_TESTING

PYTHONPATH=$RMG_TESTING:$ORIGIN_PYTHONPATH 

# use the rmgrc file to point to the location of the desired RMG-database:
rmgrc="database.directory : "$testing/RMG-database/input/
rm -rf $HOME/.rmg
mkdir -p $HOME/.rmg
echo $rmgrc >> $HOME/.rmg/rmgrc

python $RMG_TESTING/rmg.py testing/testmodel/$1/input.py > /dev/null
source deactivate
PYTHONPATH=$ORIGIN_PYTHONPATH

# compare both generated models
source activate benchmark
PYTHONPATH=$RMG_BENCHMARK:$ORIGIN_PYTHONPATH 

bash check.sh $1 testing/benchmark/$1 testing/testmodel/$1

PYTHONPATH=$ORIGIN_PYTHONPATH
source deactivate

# make folder for models generated by the test version of RMG-Py and RMG-database, with scoop enabled:
mkdir -p testing/testmodel/$1/scoop
rm -rf testing/testmodel/$1/scoop/*
cp examples/rmg/$1/input.py testing/testmodel/$1/scoop/input.py
echo "Version of RMG running with SCOOP: $RMG"
source activate testing
PYTHONPATH=$RMG_TESTING:$ORIGIN_PYTHONPATH

python -m scoop -n 1 $RMG_TESTING/rmg.py testing/testmodel/$1/scoop/input.py > /dev/null

PYTHONPATH=$ORIGIN_PYTHONPATH
source deactivate

# compare both generated models
source activate benchmark
PYTHONPATH=$RMG_BENCHMARK:$ORIGIN_PYTHONPATH 

bash check.sh $1 testing/benchmark/$1 testing/testmodel/$1/scoop

PYTHONPATH=$ORIGIN_PYTHONPATH
source deactivate