#!/bin/bash
eg=$1

export ORIGIN_PYTHONPATH=$PYTHONPATH

###########
#BENCHMARK#
###########
# make folder for models generated by the benchmark version of RMG-Py/RMG-database:
export benchmark_tests=$DATA_DIR/tests/benchmark/${benchmark_py_sha}_${benchmark_db_sha}/
mkdir -p $benchmark_tests/thermo_val_jobs/$eg

cp $BASE_DIR/examples/thermo_val/$eg/dataset.txt $benchmark_tests/thermo_val_jobs/$eg/dataset.txt

source activate ${benchmark_env}
echo "benchmark version of RMG: "$RMG_BENCHMARK
export PYTHONPATH=$RMG_BENCHMARK:$ORIGIN_PYTHONPATH 
echo "Test mode: benchmark"
python $BASE_DIR/thermo_val/evaluate.py -d $benchmark_tests/thermo_val_jobs/$eg/dataset.txt -pb master -dbb master -psha ${benchmark_py_sha} -dbsha ${benchmark_db_sha}

source deactivate
export PYTHONPATH=$ORIGIN_PYTHONPATH

#########
#TESTING#
#########
# make folder for models generated by the test version of RMG-Py and RMG-database:
export testing_tests=$DATA_DIR/tests/testing/${testing_py_sha}_${testing_db_sha}/
mkdir -p $testing_tests/thermo_val_jobs/$eg

cp $BASE_DIR/examples/thermo_val/$eg/dataset.txt $testing_tests/thermo_val_jobs/$eg/dataset.txt

source activate ${testing_env}
echo "testing version of RMG: "$RMG_TESTING
export PYTHONPATH=$RMG_TESTING:$ORIGIN_PYTHONPATH 
echo "Test mode: testing"
python $BASE_DIR/thermo_val/evaluate.py -d $testing_tests/thermo_val_jobs/$eg/dataset.txt -pb $RMG_TESTING_BRANCH -dbb $RMGDB_TESTING_BRANCH -psha ${testing_py_sha} -dbsha ${testing_db_sha}

source deactivate
export PYTHONPATH=$ORIGIN_PYTHONPATH
